### ISSUE TITLE
Missing/incorrect info: The Class Recording Links are Broken/Not Posted yet

### ISSUE THREAD

**Issue by aayush110** [comp426-2023-spring/schedule#1]
#### URL of file with the missing/incorrect info

https://github.com/comp426-2023-spring/schedule/blob/main

#### Line number with missing or incorrect info

First row of the "Session schedule" table

#### What is wrong?

The link is broken

**Comment by jdmar3** [comment]
I have updated the page and the links for the first two sessions are there and should be working now.
