### ISSUE TITLE
Missing/incorrect info: Lecture Recordings 

### ISSUE THREAD

**Issue by StevenAMartin** [comp426-2023-spring/schedule#3]
#### URL of file with the missing/incorrect info
https://github.com/comp426-2023-spring/schedule/ 
and 
https://uncch.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=19872ac0-1b5a-4093-af2a-af88015ddb9b

#### Line number with missing or incorrect info
23 & 24

#### What is wrong?
Hello just wondering when the lecture recordings for 2023-02-07 & 2023-02-09 will be posted. I attended 2023-02-07 by zoom so I really only need 2023-02-09 

#### What should be there instead?
Lecture links

**Comment by jdmar3** [comment]
They are posted with https://github.com/comp426-2023-spring/schedule/commit/b61829eaa9d6317bde27b1e2551cee1c8013b129.
